version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      # args:
      #   # [Choice] Node.js version: 14, 12, 10
      #   VARIANT: 14
      #   # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
      #   USER_UID: 1000
      #   USER_GID: 1000
    ports:
      - 8080:8080
    volumes:
      - ..:/workspace:cached
      - ./config:/config
      - /dev:/dev
    # cap_add:
    #   - SYS_ADMIN
    #   - MKNOD
    # devices:
    #   - /dev/loop24:/dev/loop24
    # entrypoint: ["/bin/bash", "-c", "/mount.sh"]
    # entrypoint: ["/bin/bash", "-c", "/mount.sh"]
    # command: ["bash", "-c", "/mount.sh"]
    privileged: true
    device_cgroup_rules:
      - b 7:* rmw
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
