services:
  workspace:
    build:
      context: .
      dockerfile: test4.Dockerfile
      args:
        UBUNTU_TAG: 20.04
        DENO_VERSION: 1.13.1
        # VARIANT: 16
        # USERNAME: vscode
      # environment:
    ports:
      - 8080:8080
      # - 3333:3000
    volumes:
      - ..:/workspace:cached
      # - ./config:/config
      - /dev:/dev
    # cap_add:
    #   - SYS_ADMIN
    #   - MKNOD
    # devices:
    #   - /dev/loop24:/dev/loop24
    privileged: true
    device_cgroup_rules:
      - b 7:* rmw
    # command: pnpm -r dev
    # command: sleep infinity
