version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../:/workspace:cached
      - ./config:/config
      - /dev:/dev
    # cap_add:
    #   - SYS_ADMIN
    #   - MKNOD
    # devices:
    #   - /dev/loop24:/dev/loop24
    privileged: true
    device_cgroup_rules:
      - b 7:* rmw
