version: "3.8"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - ..:/workspace:cached
      # - ./config:/config
      - /dev:/dev
    # cap_add:
    #   - SYS_ADMIN
    #   - MKNOD
    # devices:
    #   - /dev/loop24:/dev/loop24
    privileged: true
    device_cgroup_rules:
      - b 7:* rmw
